报这个错：  
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)

解决方案：

```py
import sys
stdi,stdo,stde=sys.stdin,sys.stdout,sys.stderr
reload(sys)
sys.stdin,sys.stdout,sys.stderr=stdi,stdo,stde
sys.setdefaultencoding('utf-8')
```


## 编码格式

有时候，乱码来自字符串的编码格式
```py
unicodestring = u"Hello world"

# 将Unicode转化为普通Python字符串："encode"  
utf8string = unicodestring.encode("utf-8")  
asciistring = unicodestring.encode("ascii")  
isostring = unicodestring.encode("ISO-8859-1")  
utf16string = unicodestring.encode("utf-16")  

# 将普通Python字符串转化为Unicode："decode"  
plainstring1 = unicode(utf8string, "utf-8")  
plainstring2 = unicode(asciistring, "ascii")  
plainstring3 = unicode(isostring, "ISO-8859-1")  
plainstring4 = unicode(utf16string, "utf-16")  

assert plainstring1 == plainstring2 == plainstring3 == plainstring4
```

## 中文注释
```py
# coding=utf-8
```
